"""empty message

Revision ID: 9b6f0777881a
Revises: 
Create Date: 2025-02-20 12:46:08.877189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6f0777881a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('birth_year', sa.String(length=25), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('height', sa.String(length=25), nullable=True),
    sa.Column('mass', sa.String(length=15), nullable=True),
    sa.Column('eye_color', sa.String(length=10), nullable=True),
    sa.Column('hair_color', sa.String(length=25), nullable=True),
    sa.Column('skin_color', sa.String(length=25), nullable=True),
    sa.Column('homeworld', sa.String(length=250), nullable=True),
    sa.Column('created', sa.String(length=100), nullable=True),
    sa.Column('edited', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_people'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('planets',
    sa.Column('id_planets', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('population', sa.String(length=25), nullable=True),
    sa.Column('climate', sa.String(length=25), nullable=True),
    sa.Column('diameter', sa.String(length=25), nullable=True),
    sa.Column('gravity', sa.String(length=15), nullable=True),
    sa.Column('orbital_period', sa.String(length=25), nullable=True),
    sa.Column('rotation_period', sa.String(length=25), nullable=True),
    sa.Column('surface_water', sa.String(length=25), nullable=True),
    sa.Column('terrain', sa.String(length=25), nullable=True),
    sa.Column('created', sa.String(length=75), nullable=True),
    sa.Column('edited', sa.String(length=75), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_planets'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=75), nullable=False),
    sa.Column('phone', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id_vehicles', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=25), nullable=True),
    sa.Column('crew', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=75), nullable=True),
    sa.Column('vehicle_class', sa.String(length=50), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=75), nullable=True),
    sa.Column('consumables', sa.String(length=50), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=25), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('passengers', sa.String(length=25), nullable=True),
    sa.Column('created', sa.String(length=100), nullable=True),
    sa.Column('edited', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_vehicles'),
    sa.UniqueConstraint('model'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('favorite_people',
    sa.Column('id_favorite_people', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['people.id_people'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorite_people')
    )
    op.create_table('favorite_planets',
    sa.Column('id_favorite_planets', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.id_planets'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorite_planets')
    )
    op.create_table('favorite_vehicles',
    sa.Column('id_favorite_vehicles', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_vehicles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_vehicles'], ['vehicles.id_vehicles'], ),
    sa.PrimaryKeyConstraint('id_favorite_vehicles')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_vehicles')
    op.drop_table('favorite_planets')
    op.drop_table('favorite_people')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
